name: Build Sakai Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      sakai_version:
        description: 'Sakai version to build'
        required: true
        default: '23.3'
        type: string
      publish_image:
        description: 'Publish image to DockerHub'
        required: true
        default: false
        type: boolean

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/sakai-lms
  # Only build for the architecture you need most - add back the other if needed
  PLATFORMS: linux/amd64

jobs:
  build-and-push:
    name: Build Sakai Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Only set up QEMU if you really need multi-platform
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      #   if: ${{ contains(env.PLATFORMS, ',') }}

      - name: Set Sakai version
        id: set-version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "SAKAI_VERSION=${{ github.event.inputs.sakai_version }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_type }}" == "tag" && "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+$ ]]; then
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#v}"
            echo "SAKAI_VERSION=${VERSION}" >> $GITHUB_ENV
          else
            echo "SAKAI_VERSION=23.3" >> $GITHUB_ENV
          fi
          echo "Using Sakai version: ${{ env.SAKAI_VERSION }}"

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=${{ env.SAKAI_VERSION }},enable=true

      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' && (github.event_name != 'workflow_dispatch' || github.event.inputs.publish_image == 'true') }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Maven caching
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ env.SAKAI_VERSION }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ env.SAKAI_VERSION }}-
            ${{ runner.os }}-maven-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' && (github.event_name != 'workflow_dispatch' || github.event.inputs.publish_image == 'true') }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SAKAI_VERSION=${{ env.SAKAI_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max